### ISSUE TITLE
No reconnect after connection to OPC server is lost

### ISSUE THREAD

**Issue by cskowronnek** [elastic/Machinebeat#10]
Machinebeat does not reconnect to the OPC nodes when the connection to the OPC server is interrupted. It states "Published 0 events" forever.

**Comment by felix-lessoer** [comment]
This should be fixed now. There will be a reconnect whenever there are multiple 0 publish events in a series.

**Comment by cskowronnek** [comment]
Tested manually. Seems to work. Thank you very much
