### ISSUE TITLE
ARM build

### ISSUE THREAD

**Issue by cskowronnek** [elastic/Machinebeat#15]
We would like to run Machinebeat on a Raspberry Pi 4. Is it possible to cross compile for ARM8?

**Comment by felix-lessoer** [comment]
Just build it for ARM8. Could you check that it is working for you?
https://ela.st/machinebeat-arm

**Comment by cskowronnek** [comment]
Unfortunately our RPi 4 is still running on a 32-bit kernel as the 64-bit kernel is still experimental. Could you build a 32-bit ARM version as well? 
```
:~/machinebeat $ ./machinebeat -c machinebeat.yml -e 
bash: ./machinebeat: Kann die Binärdatei nicht ausführen: Fehler im Format der Programmdatei
:~/machinebeat $ uname -a
Linux pit-dashboard 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
:~/machinebeat $ file machinebeat
machinebeat: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=ZkCFiY1nlW9HGcMH_dyD/Ucjuk0MTg9dHCVbUyaTj/EvWSMw-4PdQOtQjiuvqS/YTz_cwizH3r5efmVxXVP, not stripped
```

**Comment by felix-lessoer** [comment]
I used ARM8 based in this documentation:
https://github.com/golang/go/wiki/GoArm

ARM7 seems to be for 32bit

**Comment by felix-lessoer** [comment]
Same link but it contains the arm7 version now.

**Comment by cskowronnek** [comment]
Thanks! The binary runs. I'll ship it to our test device and see if it runs stable

**Comment by cskowronnek** [comment]
The build runs stable on two Raspberry Pi 4 until now.

**Comment by felix-lessoer** [comment]
Sounds like we can close that issue :)

**Comment by cskowronnek** [comment]
Yes, we can. Could you please build future version also for ARM?
