### ISSUE TITLE
Issue with Node Configurations in OPCUA.yml

### ISSUE THREAD

**Issue by CompsAndData** [elastic/Machinebeat#20]
Hello,

I am attempting to collect data from specific nodes from a Kepware OPC server.  I have added specific tags to the node configuration section and I have tried to turn browsing off.  Attached is the opcua.yml config file and some debug info.  When I try to start machinebeat, it appears that it tries to browse anyway and other information is being sent to Elastic.

Thanks for any help!

[log.txt](https://github.com/elastic/Machinebeat/files/5052952/log.txt)

[opcua.txt](https://github.com/elastic/Machinebeat/files/5052940/opcua.txt)

**Comment by felix-lessoer** [comment]
You need to set 
`browse.enabled: false`
The other notion is not working anymore.

**Comment by CompsAndData** [comment]
Thanks so much that worked perfect!
