### ISSUE TITLE
kepware opcua connection result inquiry.

### ISSUE THREAD

**Issue by Buungi** [elastic/Machinebeat#25]
Hello. Thank you for developing machinebeat.

I used machinebeat to connect with kepware opcua.

The connection seems to be fine,
The data to be imported is not the node value that I want.

As shown in the image id: "ns=2;s=Accura/Accura2300/Current"
I want to bring the value
Keep getting the value "opcua.node.ID i=2258".

What should I modify to get the correct value?
Please help me.

opcua.yml

![image](https://user-images.githubusercontent.com/9245441/91386645-6f535400-e86e-11ea-8bfe-d1cc852180e8.png)

result

![image](https://user-images.githubusercontent.com/9245441/91386440-f6ec9300-e86d-11ea-9841-51ee78c12488.png)

**Comment by felix-lessoer** [comment]
I guess `browse.enabled : false` would help.

If you send the logs I can tell you more.

**Comment by Buungi** [comment]
Thanks for the answer.

I've already used that option. "browse.enabled: false"
Even if I try again, it is the same as before.

Below is the log information that I ran.
![image](https://user-images.githubusercontent.com/9245441/91400956-8fd5db00-e87b-11ea-91a5-1db0388689df.png)
![image](https://user-images.githubusercontent.com/9245441/91401230-b4ca4e00-e87b-11ea-994f-e05789224db0.png)

Thank you.

**Comment by felix-lessoer** [comment]
As you can see in the logs its still browsing. 
So your browse configuration is not set correctly. 

Make sure that the intention is right.

**Comment by Buungi** [comment]
Thank you.

That case was resolved.

browse:
  -enabled: false

This can't get the tag value

browse.enabled: false

This gets the tag value.
