### ISSUE TITLE
OPCUA: No boolean values if browse options explictily set

### ISSUE THREAD

**Issue by cskowronnek** [elastic/Machinebeat#26]
The default opcua.yml looks like this:
```
  ##The browse mode is enabled at default
  ## This means, if the configured nodes have childs all subscribable nodes will be monitored
  #browse.enabled: true
  #browse.maxLevel: 3
  #browse.maxNodePerParent: 5
```
If I uncomment the browse options machinebeat still works but is not subscribing or polling data points with opcua.node.DataType "bool"

**Comment by felix-lessoer** [comment]
Is the subscribe working if this is in the default configuration?
Are you sure that the bool nodes are included into the browse when you set maxLevel and maxNodePerParent?

If your answer to both is yes: Could you run debug logs and send it to me?
