### ISSUE TITLE
Documentation link not valid

### ISSUE THREAD

**Issue by Glagnar** [elastic/Machinebeat#27]
I am looking at the mqtt.yml.disabled file and the link:
https://www.elastic.co/guide/en/beats/machinebeat/machinebeat-module-mqtt.html

Does not work.

**Comment by felix-lessoer** [comment]
Thanks @Glagnar . You are right. 
Machinebeat is still in experimental state and has no dedicated documenation.

However the MQTT part has already been migrated into the official beats suite.
You can find it here: https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-mqtt.html
