### ISSUE TITLE
Using Putty Terminal to install Machinebeat and collect data over OPC/MQTT into Logstach

### ISSUE THREAD

**Issue by Valdos116** [elastic/Machinebeat#34]
I just started exploring elastic search and was trying to install machinebeat Linus/windows version via putty. Are there any documentation on how to proceed (steps) and set of line commands to accomplish this?

Thanks

**Comment by felix-lessoer** [comment]
Describe your current Situation and target pls.
There no other documentation than what you can find in this GitHub repo.
