### ISSUE TITLE
How to run machinebeat as service

### ISSUE THREAD

**Issue by Valdos116** [elastic/Machinebeat#39]
Guys,
I have machinebeat set up and up and running. The only problem is that it's tied to the user logins. My question is how to run it as a service?

Thanks,

**Comment by cskowronnek** [comment]
My /etc/systemd/system/machinebeat.service 

```
[Info]
Description=Machinebeat to collect MQTT and OPC UA messages

[Service]
User=root
Type=simple
TimeoutSec=0
PIDFile=/var/run/machinebeat.pid
ExecStart=/bin/sh -c '/usr/share/machinebeat/machinebeat -c /usr/share/machinebeat/machinebeat.yml -path.logs /var/log/machinebeat'
KillMode=mixed

Restart=on-failure
RestartSec=42s

StandardOutput=/var/log/machinebeat.log
StandardError=/var/log/machinebeaterr.log

[Install]
WantedBy=default.target
```

**Comment by Valdos116** [comment]
Thanks for the answer. Can't locate machinebeat.service in my system directory.Here is in that directory

drwxr-xr-x. 2 root root   31 May 13  2020 basic.target.wants
drwxr-xr-x. 2 root root   31 May 13  2020 bluetooth.target.wants
lrwxrwxrwx. 1 root root   41 May 13  2020 dbus-org.bluez.service -> /usr/lib/systemd/system/bluetooth.service
lrwxrwxrwx. 1 root root   41 May 13  2020 dbus-org.fedoraproject.FirewallD1.service -> /usr/lib/systemd/system/firewalld.service
lrwxrwxrwx. 1 root root   44 May 13  2020 dbus-org.freedesktop.Avahi.service -> /usr/lib/systemd/system/avahi-daemon.service
lrwxrwxrwx. 1 root root   44 May 13  2020 dbus-org.freedesktop.ModemManager1.service -> /usr/lib/systemd/system/ModemManager.service
lrwxrwxrwx. 1 root root   57 May 13  2020 dbus-org.freedesktop.nm-dispatcher.service -> /usr/lib/systemd/system/NetworkManager-dispatcher.service
lrwxrwxrwx. 1 root root   56 Apr  9  2020 dbus-org.freedesktop.resolve1.service -> ../../../usr/lib/systemd/system/systemd-resolved.service
lrwxrwxrwx. 1 root root   41 May 13  2020 dbus-org.freedesktop.timedate1.service -> /usr/lib/systemd/system/timedatex.service
lrwxrwxrwx. 1 root root   36 May 13  2020 default.target -> /lib/systemd/system/graphical.target
lrwxrwxrwx. 1 root root   35 May 13  2020 display-manager.service -> /usr/lib/systemd/system/gdm.service
drwxr-xr-x. 2 root root   32 May 13  2020 getty.target.wants
drwxr-xr-x. 2 root root   88 May 14  2020 graphical.target.wants
-rw-r--r--. 1 root root  636 Mar 18 01:09 kibana.service
-rw-r--r--. 1 root root  670 Apr 23 17:20 logstash.service
drwxr-xr-x. 2 root root 4096 Jul  7 14:42 multi-user.target.wants
drwxr-xr-x. 2 root root   48 May 13  2020 network-online.target.wants
drwxr-xr-x. 2 root root   33 May 13  2020 nfs-blkmap.service.requires
drwxr-xr-x. 2 root root   33 May 13  2020 nfs-idmapd.service.requires
drwxr-xr-x. 2 root root   33 May 13  2020 nfs-mountd.service.requires
drwxr-xr-x. 2 root root   33 May 13  2020 nfs-server.service.requires
drwxr-xr-x. 2 root root   26 May 13  2020 printer.target.wants
drwxr-xr-x. 2 root root   31 May 13  2020 remote-fs.target.wants
drwxr-xr-x. 2 root root   33 May 13  2020 rpc-gssd.service.requires
drwxr-xr-x. 2 root root   33 May 13  2020 rpc-statd-notify.service.requires
drwxr-xr-x. 2 root root   33 May 13  2020 rpc-statd.service.requires
drwxr-xr-x. 2 root root  258 Apr 23 08:58 sockets.target.wants
drwxr-xr-x. 2 root root  254 May 13  2020 sysinit.target.wants
lrwxrwxrwx. 1 root root   39 May 13  2020 syslog.service -> /usr/lib/systemd/system/rsyslog.service
lrwxrwxrwx. 1 root root    9 May 11  2019 systemd-timedated.service -> /dev/null
drwxr-xr-x. 2 root root   34 May 13  2020 timers.target.wants
drwxr-xr-x. 2 root root   29 May 13  2020 vmtoolsd.service.requires

**Comment by felix-lessoer** [comment]
Thanks @cskowronnek for sending the file.

@Valdos116 : You need to create the file yourself. After doing that you should be able to start the service using e.g. `systemctl start machinebeat`

**Comment by cskowronnek** [comment]
And you can enable autostart at system stat with:

systemctl enable machinebeat

**Comment by Valdos116** [comment]
Thanks @felix-lessoer and @cskowronnek
I've created machinebeat.service file in /etc/systemd/system.I copied and pasted the file that @cskowronnek posted above.
When I run machinebeat.service with "systemctl start machinebeat", I received the following error "_Failed to start machinebeat.service: Unit machinebeat.service has a bad unit file setting"._And when I checked its status I got the logs:

machinebeat.service
Loaded: bad-setting (Reason: Unit machinebeat.service has a bad unit file setting.)
Active: inactive (dead)

Sep 01 09:57:22 systemd[1]: /etc/systemd/system/machinebeat.service:8: Assignment outside of section. Igno>
Sep 01 09:57:22 systemd[1]: /etc/systemd/system/machinebeat.service:9: Assignment outside of section. Igno>
Sep 01 09:57:22 systemd[1]: /etc/systemd/system/machinebeat.service:10: Assignment outside of section. Ign>
Sep 01 09:57:22 systemd[1]: /etc/systemd/system/machinebeat.service:11: Assignment outside of section. Ign>
Sep 01 09:57:22 systemd[1]: /etc/systemd/system/machinebeat.service:13: Assignment outside of section. Ign>
Sep 01 09:57:22 systemd[1]: /etc/systemd/system/machinebeat.service:14: Assignment outside of section. Ign>
Sep 01 09:57:22 systemd[1]: /etc/systemd/system/machinebeat.service:16: Assignment outside of section. Ign>
Sep 01 09:57:22 systemd[1]: /etc/systemd/system/machinebeat.service:17: Assignment outside of section. Ign>
Sep 01 09:57:22 systemd[1]: /etc/systemd/system/machinebeat.service:20: Assignment outside of section. Ign>
Sep 01 09:57:22 systemd[1]: machinebeat.service: Service lacks both ExecStart= and ExecStop= setting. Refu>
lines 1-14/14 (END)

Any thoughts?

**Comment by Valdos116** [comment]
Thanks @cskowronnek  and @felix-lessoer
