### ISSUE TITLE
log4j vulnerability clarifications

### ISSUE THREAD

**Issue by pankaj-k** [elastic/Machinebeat#41]
Hi,

I am not sure if this is right way of getting this information. 
But is this component affected by log4j vulnerability? And if so will you be making a release just to patch up the issue?

Regards
PK

**Comment by felix-lessoer** [comment]
elastic is taking care of the log4j vulnerability in all components. 
I will update to the latest beats framework to make sure to include all changes that have happened in regards to that.

**Comment by felix-lessoer** [comment]
Upgraded to the latest version of all dependencies. 
If it was vulnerable this should be fixed now.
