### ISSUE TITLE
username and password in opcua.yml

### ISSUE THREAD

**Issue by raj885** [elastic/Machinebeat#6]
Hi, 
I am trying to ingest data from OPC-UA to Elasticsearch. I wonder how to  pass username and password in the opcua.yml. I tried by giving simply username and password, however it is not working. Please let me know if it is possible

- module: opcua
  metricsets: ["nodevalue"]
  enabled: true
  period: 2s
  endpoint: "opc.tcp://{server}:port"
  username: "username"
  password: "password"

**Comment by felix-lessoer** [comment]
Security for OPC-UA is now added to the module. Would be great if you can check that its work for you.
